MODEL_IDS:
  cross_encoder: "cross-encoder/ms-marco-MiniLM-L-12-v2"
  embedding_model: "sentence-transformers/all-mpnet-base-v2"
  llm: "meta-llama/Meta-Llama-3-8B-Instruct"
  zero_shot_classifier: "MoritzLaurer/deberta-v3-large-zeroshot-v2.0"
API_KEYS:
  # to be implemented 
TASKS:

  # Query Tasks
  - name: "PreprocessQueryTask"
    class: logic.tasks.query_processing.preprocess_query.PreprocessQueryTask
  
  - name: "ReformulateQueryTask"
    class: logic.tasks.query_processing.reformulate_query.ReformulateQueryTask

  - name: "DecomposeQueryTask"
    class: logic.tasks.query_processing.decompose_query.DecomposeQueryTask

    # Classification Tasks
  - name: "ClassifyQueryTask"
    class: logic.tasks.classification.classify_query.ClassifyQueryTask

  - name: "ClassifyMultistepQueryTask"
    class: logic.tasks.classification.classify_multistep_query.ClassifyMultistepQueryTask

    # Retrieval Tasks
  - name: "EmbedQueryTask"
    class: logic.tasks.retrieval.embed_query.EmbedQueryTask

  - name: "RetrieveDocumentsTask"
    class: logic.tasks.retrieval.retrieve_documents.RetrieveDocumentsTask

  - name: "FilterDocumentsTask"
    class: logic.tasks.retrieval.filter_documents.FilterDocumentsTask

  - name: "ReRankingTask"
    class: logic.tasks.retrieval.rerank_documents.ReRankingTask

    # Response Tasks
  - name: "GenerateResponseTask"
    class: logic.tasks.response.generate_response.GenerateResponseTask

  - name: "GradeResponseTask"
    class: logic.tasks.response.grade_response.GradeResponseTask

ROUTING:
  # Query Tasks
  PreprocessQueryTask:
    default: "ClassifyQueryTask"

  ReformulateQueryTask:
    default: "DecomposeQueryTask"

  DecomposeQueryTask:
    default: "EmbedQueryTask"

  # Classifying 
  ClassifyQueryTask:
    question: "EmbedQueryTask" # "ClassifyMultistepQueryTask"
    command: "EmbedQueryTask" #"ClassifyMultistepQueryTask"
    default: "GenerateResponseTask"
  
  ClassifyMultistepQueryTask:
    multistep: "ReformulateQueryTask"
    not_multistep: "EmbedQueryTask"



  # Default RAG
  EmbedQueryTask:
    default: "RetrieveDocumentsTask"
  RetrieveDocumentsTask:
    default: "ReRankingTask" #FilterDocumentsTask
  FilterDocumentsTask:
    default: "ReRankingTask"
  ReRankingTask:
    default: "GenerateResponseTask"

  # Response generation and evaluation
  GenerateResponseTask: 
    grade: "GradeResponseTask"
    end: "EndTask"

  GradeResponseTask:
    end: "EndTask"


DATABASE: 
  # add when we got persistent data.