query_processing_pipeline:
  - PreprocessQueryTask
  - ClassifyQueryTask 

retrieval_pipeline:
  - RetrieveDocumentsTask
  - ReRankingTask 
  - DocumentRemoval 

response_generation_task: GenerateResponseTask
response_grading_task: GradeResponseTask