routing_rules:
  PreprocessQueryTask: ClassifyQueryTask
  ClassifyQueryTask:
    course_query: DecomposeQueryTask
    general_query: RetrieveDocumentsTask
  DecomposeQueryTask: RetrieveDocumentsTask
  RetrieveDocumentsTask: ReRankingTask
  ReRankingTask: DocumentRemoval
  DocumentRemoval: GenerateResponseTask
  GenerateResponseTask: GradeResponseTask
  GradeResponseTask: null