TASKS:
  - name: "PreprocessQueryTask"
    class: src.tasks.preprocess_query.PreprocessQueryTask
    services:
      - text_generation

  - name: "ClassifyQueryTask"
    class: src.tasks.classify_query.ClassifyQueryTask
    services:
      - classification

  - name: "RetrieveDocumentsTask"
    class: src.tasks.retrieve_documents.RetrieveDocumentsTask
    services:
      - document_retrieval


  - name: "ReRankingTask"
    class: src.tasks.rerank_documents.ReRankingTask
    services:
      - reranking
      
  - name: "FilterDocumentsTask"
    class: src.tasks.filter_documents.FilterDocumentsTask
    services:
      - text_generation

  - name: "TransformRetrievedDocumentsTask"
    class: src.tasks.transform_retrieved_documents.TransformRetrievedDocumentsTask
    services:
      - text_generation

  - name: "TwoStepResponseGenerationTask"
    class: src.tasks.two_step_response_generation.TwoStepResponseGenerationTask
    services:
      - text_generation

  - name: "GenerateResponseTask"
    class: src.tasks.generate_response.GenerateResponseTask
    services:
      - text_generation

  - name: "GradeResponseTask"
    class: src.tasks.grade_response.GradeResponseTask
    services:
      - text_generation


ROUTING:

# PRE-RETRIEVAL
  PreprocessQueryTask:
    default: "ClassifyQueryTask"

  ClassifyQueryTask:
    question: "RetrieveDocumentsTask"
    command: "RetrieveDocumentsTask"
    default: "GenerateResponseTask"


# RETRIEVAL
  RetrieveDocumentsTask:
    default: "ReRankingTask"


# POST-RETRIEVAL
  ReRankingTask:
    default: "FilterDocumentsTask"

  FilterDocumentsTask:
    no_context: "GenerateResponseTask"
    default: "TransformRetrievedDocumentsTask"
  
  TransformRetrievedDocumentsTask:
    default: "TwoStepResponseGenerationTask"


# GENERATION
  TwoStepResponseGenerationTask:
    default: "EndTask"

  GenerateResponseTask: 
    grade: "GradeResponseTask"
    end: "EndTask"


# POST-GENERATION
  GradeResponseTask:
    end: "EndTask"
