
TASKS:

  # Query Tasks
  - name: "PreprocessQueryTask"
    class: src.tasks.preprocess_query.PreprocessQueryTask
    services:
      - text_generation

    # Classification Tasks
  - name: "ClassifyQueryTask"
    class: src.tasks.classify_query.ClassifyQueryTask
    services:
      - classification

    # Retrieval Tasks
  - name: "RetrieveDocumentsTask"
    class: src.tasks.retrieve_documents.RetrieveDocumentsTask
    services:
      - document_retrieval


  - name: "ReRankingTask"
    class: src.tasks.rerank_documents.ReRankingTask
    services:
      - reranking
    # Response Tasks
      
  - name: "FilterDocumentsTask"
    class: src.tasks.filter_documents.FilterDocumentsTask
    services:
      - text_generation

  - name: "TransformRetrievedDocumentsTask"
    class: src.tasks.transform_retrieved_documents.TransformRetrievedDocumentsTask
    services:
      - text_generation

  - name: "TwoStepResponseGenerationTask"
    class: src.tasks.two_step_response_generation.TwoStepResponseGenerationTask
    services:
      - text_generation

  - name: "GenerateResponseTask"
    class: src.tasks.generate_response.GenerateResponseTask
    services:
      - text_generation

  - name: "GradeResponseTask"
    class: src.tasks.grade_response.GradeResponseTask
    services:
      - text_generation


ROUTING:

  PreprocessQueryTask:
    default: "ClassifyQueryTask"

  ClassifyQueryTask:
    question: "RetrieveDocumentsTask"
    command: "RetrieveDocumentsTask"
    default: "GenerateResponseTask"

  RetrieveDocumentsTask:
    default: "ReRankingTask"
  
  ReRankingTask:
    default: "FilterDocumentsTask"
  FilterDocumentsTask:
    default: "TransformRetrievedDocumentsTask"
  
  TransformRetrievedDocumentsTask:
    default: "TwoStepResponseGenerationTask"

  TwoStepResponseGenerationTask:
    default: "EndTask"



  GenerateResponseTask: 
    grade: "GradeResponseTask"
    end: "EndTask"

  GradeResponseTask:
    end: "EndTask"

