MODEL_IDS:
  cross_encoder: "cross-encoder/ms-marco-MiniLM-L-12-v2"
  embedding_model: "sentence-transformers/all-mpnet-base-v2"
  llm: "meta-llama/Meta-Llama-3-8B-Instruct"
  zero_shot_classifier: "MoritzLaurer/deberta-v3-large-zeroshot-v2.0"
API_KEYS:
  # to be implemented 
TASKS:

  # Query Tasks
  - name: "PreprocessQueryTask"
    class: src.tasks.preprocess_query.PreprocessQueryTask
  
  - name: "ReformulateQueryTask"
    class: src.tasks.reformulate_query.ReformulateQueryTask

  - name: "DecomposeQueryTask"
    class: src.tasks.decompose_query.DecomposeQueryTask

    # Classification Tasks
  - name: "ClassifyQueryTask"
    class: src.tasks.classify_query.ClassifyQueryTask

  - name: "ClassifyMultistepQueryTask"
    class: src.tasks.classify_multistep_query.ClassifyMultistepQueryTask

    # Retrieval Tasks
  - name: "EmbedQueryTask"
    class: src.tasks.embed_query.EmbedQueryTask

  - name: "RetrieveDocumentsTask"
    class: src.tasks.retrieve_documents.RetrieveDocumentsTask

  - name: "FilterDocumentsTask"
    class: src.tasks.filter_documents.FilterDocumentsTask

  - name: "ReRankingTask"
    class: src.tasks.rerank_documents.ReRankingTask

    # Response Tasks
  - name: "GenerateResponseTask"
    class: src.tasks.generate_response.GenerateResponseTask

  - name: "GradeResponseTask"
    class: src.tasks.grade_response.GradeResponseTask

ROUTING:

    # Response Tasks
  - name: "GenerateResponseTask"
    class: src.tasks.generate_response.GenerateResponseTask

  - name: "GradeResponseTask"
    class: src.tasks.grade_response.GradeResponseTask

ROUTING:

  PreprocessQueryTask:
    default: "ClassifyQueryTask"
  ReformulateQueryTask:
    default: "DecomposeQueryTask"
  DecomposeQueryTask:
    default: "RetrieveDocumentsTask"

  ClassifyQueryTask:
    question: "RetrieveDocumentsTask" 
    command: "RetrieveDocumentsTask"  
    default: "GenerateResponseTask"
  ClassifyMultistepQueryTask:
    multistep: "ReformulateQueryTask"
    not_multistep: "RetrieveDocumentsTask" 

  EmbedQueryTask:
    default: "RetrieveDocumentsTask"
  RetrieveDocumentsTask:
    default: "ReRankingTask"
  FilterDocumentsTask:
    default: "ReRankingTask"
  ReRankingTask:
    default: "GenerateResponseTask"

  GenerateResponseTask: 
    grade: "GradeResponseTask"
    end: "EndTask"

  GradeResponseTask:
    end: "EndTask"


DATABASE: 
  # add when we got persistent data.