starting_task: PreprocessQueryTask
tasks:
  PreprocessQueryTask:
    next_tasks:
      default: ClassifyQueryTask
  ClassifyQueryTask:
    next_tasks:
      course_query: DecomposeQueryTask
      general_query: GenerateResponseTask
  DecomposeQueryTask:
    next_tasks:
      default: RetrieveDocumentsTask 
  RetrieveDocumentsTask:
    next_tasks:
      default: DocumentRemovalTask 
  DocumentRemovalTask:
    next_tasks:
      default: ReRankingTask 
  ReRankingTask:
    next_tasks:
      default: GenerateResponseTask 
  GenerateResponseTask:
    next_tasks:
      default: GradeResponseTask
  GradeResponseTask:
    next_tasks:
      default: EndTask